### ISSUE TITLE
Suggestion to modify line 113 of controllers/client.rb to accommodate non-UTF-8 code in some large model license files. 

### ISSUE THREAD

**Issue by lukefan** [gbaptista/ollama-ai#1]
Suggestion to modify line 113 of controllers/client.rb to accommodate non-UTF-8 code in some large model license files. 
Currently, using the yi model results in errors. 
There is an error when executing 
client.show({name: 'yi:latest'}). 
I resolved the issue by adding force_encoding. Everthing is ok.

from
partial_json += chunk
to
partial_json += chunk.force_encoding('UTF-8')

**Comment by gbaptista** [comment]
@lukefan Hey, thanks for reporting the issue! It's [fixed](https://github.com/gbaptista/ollama-ai/pull/2) and already available in [version 1.2.1](https://github.com/gbaptista/ollama-ai/releases/tag/v1.2.1).
